### ISSUE TITLE
Unable to set preset, reverb, etc

### ISSUE THREAD

**Issue by thsamajiki** [khaouitiabdelhakim/ProSoundEQ#1]
Imported ProSoundEQ dependency in gradle properly.
However, I can't set preset, reverb when I access ProSoundEQ Activity.
Seems like it is unabled, but cannot find out what is the cause.

![image](https://github.com/khaouitiabdelhakim/ProSoundEQ/assets/60818655/8d59bfd4-de7f-4116-b46c-73043977ba7a)

I used media3-exoplayer instead of MediaPlayer for greater performance.

Here is my code below.

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)

        exoPlayer = ExoPlayer.Builder(this).build()

        ProSoundEQSettings.init(exoPlayer.audioSessionId)

        // Set a listener for when the media file is ready
        exoPlayer?.addListener(object : Player.Listener {
                    override fun onIsPlayingChanged(isPlaying: Boolean) {
                        super.onIsPlayingChanged(isPlaying)
                        ......
                    }

                    override fun onMediaItemTransition(mediaItem: MediaItem?, reason: Int) {
                        super.onMediaItemTransition(mediaItem, reason)
                        ......
                    }

                    override fun onPlaybackStateChanged(state: Int) {
                        super.onPlaybackStateChanged(state)
                        ......
                    }
        })

        // Opening the equalizer
        binding.buttonSetting.setOnClickListener {
                startActivity(Intent(this, ProSoundEQ::class.java))
        }
```

**Comment by khaouitiabdelhakim** [comment]
Hey bro, thanks for using my library, I have a question have you try to click the switch above, or is the switch not working?

**Comment by khaouitiabdelhakim** [comment]
The switch right above
![324195570-8d59bfd4-de7f-4116-b46c-73043977ba7a.png](https://github.com/khaouitiabdelhakim/ProSoundEQ/assets/115430366/76f7ef55-5acb-4cea-83da-2534a7669d65)

**Comment by khaouitiabdelhakim** [comment]
Let me know!

**Comment by thsamajiki** [comment]
I did, but nothing happens..

**Comment by khaouitiabdelhakim** [comment]
what did you do? click the switch button

**Comment by khaouitiabdelhakim** [comment]
I'm using it here with media player MPlayerX you can check it out at https://play.google.com/store/apps/details?id=com.abdelhakim.music

![WhatsApp Image 2024-04-23 at 03 37 19_e45b3437](https://github.com/khaouitiabdelhakim/ProSoundEQ/assets/115430366/b92069e1-3a48-4d59-a42d-45675dfdc7be)

**Comment by khaouitiabdelhakim** [comment]
and I'm using it here in my Faborfy android app using ExoPlayer and its working just for some sounds it doas not work great!
check it out at https://play.google.com/store/apps/details?id=com.abdelhakim.faborfy

![WhatsApp Image 2024-04-23 at 03 37 19_be7140d4](https://github.com/khaouitiabdelhakim/ProSoundEQ/assets/115430366/4d79c15f-7bc0-4dce-bfa7-5b99b3952e23)

**Comment by khaouitiabdelhakim** [comment]
for you it does not even show the color lines of the equalizer? or what exactly?

**Comment by thsamajiki** [comment]
I posted .gif image of prosoundeq in my application, and please check it out.
https://blog.naver.com/ant1102/223424443461

**Comment by khaouitiabdelhakim** [comment]
I saw it bro, but have you checked out my 2 apps above? Is the audio playing in your app? 
I'm saying this, because my second app Faborfy is using the ExoPlayer as you.

I'm suing exoplayer inside a service

`var mediaPlayer: ExoPlayer? = null
    private lateinit var mediaSession : MediaSessionCompat
    lateinit var audioManager: AudioManager`

**Comment by thsamajiki** [comment]
I checked out your two apps, and the audio played well...
but prosoundeq never works well with my app..

My Gradle Version is 8.0 and Gradle Plugin Version is 8.1.1.

Even though I added the code below, still unable to use the prosoundeq functions.

AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

settings.gradle.kts
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
    }
}
```

**Comment by khaouitiabdelhakim** [comment]
I am using the 34 android sdk not the 33

**Comment by thsamajiki** [comment]
Finally solved the problem by clean project and rebuild.
Still don't know what's the cause, but it's okay...

**Comment by khaouitiabdelhakim** [comment]
Good job bro 🥳🥳🥳
